server:
  port: 8081
  address: 127.0.0.1
spring:
  security:
    user:
      name: jmw
      password: jmw
#  application:
#    name: Trie
#  profiles:
#    active: dev
#  cloud:
#    nacos:
#      server-addr: 152.136.154.249:8848
#      config:
#        file-extension: yaml
#        username: nacos
#        password: nacos


#logging:
#  config: classpath:logback.xml
#  file:
#    path: log
#  pattern:
#    file: '%d %5p - %m%n'

provider-entity:
  runnableThreadNum: 3
  name: 123
  source: 123
  data-sources:
    - type: MYSQL
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: db1
      password: SGTSKZ6jfHzPs6c7
      url: jdbc:mysql://152.136.154.249:3306/information_schema?&allowMultiQueries=true&characterEncoding=utf-8
      sql-code:
        - sql: "select CHARACTER_SET_NAME from CHARACTER_SETS"
          str: username
          load-on: local
      use-sql: true
      load-on: local
    - type: MYSQL
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: db2
      password: D4f3krSD4hBxabhR
      url: jdbc:mysql://152.136.154.249:3306/information_schema?&allowMultiQueries=true&characterEncoding=utf-8
      sql-code :
        - sql: "select DEFAULT_COLLATE_NAME from CHARACTER_SETS"
          str: username
          load-on: remote_repository
      use-sql: true
      load-on: remote_repository
    - type: MYSQL
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: db3
      password: GmNZzwWnd6kYA6X6
      url: jdbc:mysql://152.136.154.249:3306/information_schema?&allowMultiQueries=true&characterEncoding=utf-8
      sql-code:
        - sql: "select DESCRIPTION from CHARACTER_SETS"
          str: username
          load-on: mix
      use-sql: true
      load-on: mix
#    - type: MONGODB
#      driver-class-name: com.cn.jmw.driver.DefaultNonRelationalDataBaseDriver
#      url: mongodb://Mongo:123456@152.136.154.249:27017/Mongo
#      sql-code:
#        - sql: "select * from mycollection"
#          str: name
#          load-on: mix
  load-on: remote_repository
  persistence-path: h2
